readme; bun; version check

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -12,16 +12,24 @@ jobs:
     steps:
       - uses: actions/checkout@v4
 
-      - uses: actions/setup-node@v4
+      - uses: oven-sh/setup-bun@v2
         with:
-          node-version: 20
-          cache: "npm"
+          bun-version: latest
           registry-url: "https://registry.npmjs.org"
 
-      - run: npm ci
+      - run: |
+          PUBLISHED=$(npm view $(jq -r .name package.json) version)
+          LOCAL=$(jq -r .version package.json)
 
-      - run: npm run build
+          if [ "$PUBLISHED" = "$LOCAL" ]; then
+            echo "Error: Version $LOCAL is already published."
+            exit 1
+          fi
 
-      - run: npm publish --access public
+      - run: bun install
+
+      - run: bun run build
+
+      - run: bun run publish --access public
         env:
           NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
